version: 1
game_engine: gbx-custom
tag_space: 64M
extend_limits: true
scenarios:
  - keymind/the_flood/levels/multiplayer/foundation/treason_dev
  - keymind/the_flood/levels/multiplayer/bleed_it_out/bleed_it_out_dev
  - keymind/the_flood/levels/multiplayer/bridge/last_voyage_dev
commands:
  package:
    - rm -rf dist
    - mkdir -p dist
    - mercury luabundle
    - mercury luabundle bleed
    - mercury luabundle voyage
    - cp dist/*.lua package/lua-map/
    - mercury pack package/ dist/
    - rm package/lua-map/*.lua
  release:
    - mercury build --release --output package/game-maps/
    - mercury build package