version: 1
user: gravemind
cloudpath: Keymind/Projects
engine: gbx-custom
tagsize: 64M
extendlimits: true
scenarios:
  - keymind/the_flood/levels/multiplayer/astray/astray
  - keymind/the_flood/levels/multiplayer/foundation/treason_dev
  - keymind/halo_3/levels/multiplayer/bunkerworld/bunkerworld
outputpath: package/game-maps
